create table product (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	provider VARCHAR(50) NOT NULL,
	name VARCHAR(50) NOT NULL,
	price INT NOT NULL,
	details TEXT,
	avaliable BOOLEAN NOT NULL
);

insert into product (provider, name, price, details, avaliable) values ('Voonder', 'Bread - Kimel Stick Poly', 911, 'Donec ut dolor.', true);
insert into product (provider, name, price, details, avaliable) values ('Brightdog', 'Table Cloth 81x81 White', 670, 'In sagittis dui vel nisl.', true);
insert into product (provider, name, price, details, avaliable) values ('Ozu', 'Onions Granulated', 380, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', false);
insert into product (provider, name, price, details, avaliable) values ('Zoovu', 'Cake - Box Window 10x10x2.5', 698, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true);
insert into product (provider, name, price, details, avaliable) values ('Fivespan', 'Wine - Red, Mosaic Zweigelt', 357, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', false);
insert into product (provider, name, price, details, avaliable) values ('Yata', 'Wine - Fume Blanc Fetzer', 600, 'In congue.', false);
insert into product (provider, name, price, details, avaliable) values ('Blogtag', 'Gatorade - Fruit Punch', 787, 'Maecenas rhoncus aliquam lacus.', false);
insert into product (provider, name, price, details, avaliable) values ('Realpoint', 'Nutmeg - Ground', 809, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', false);
insert into product (provider, name, price, details, avaliable) values ('Kayveo', 'Wine - Winzer Krems Gruner', 37, 'Donec quis orci eget orci vehicula condimentum.', false);
insert into product (provider, name, price, details, avaliable) values ('Skynoodle', 'Soup Campbells Split Pea And Ham', 70, 'In eleifend quam a odio. In hac habitasse platea dictumst.', false);
insert into product (provider, name, price, details, avaliable) values ('Feedbug', 'Cheese - Cheddar, Old White', 800, 'Sed ante. Vivamus tortor.', true);
insert into product (provider, name, price, details, avaliable) values ('Skiba', 'Yeast - Fresh, Fleischman', 360, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', true);
insert into product (provider, name, price, details, avaliable) values ('Kayveo', 'Wine - Niagara,vqa Reisling', 45, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', false);
insert into product (provider, name, price, details, avaliable) values ('Realbuzz', 'Cheese - Brie,danish', 836, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', false);
insert into product (provider, name, price, details, avaliable) values ('Topiczoom', 'Water - Spring Water 500ml', 834, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', true);
insert into product (provider, name, price, details, avaliable) values ('Yakidoo', 'Pate - Peppercorn', 143, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', false);
insert into product (provider, name, price, details, avaliable) values ('Dabshots', 'Rabbit - Legs', 719, 'In quis justo.', false);
insert into product (provider, name, price, details, avaliable) values ('Edgewire', 'Langers - Mango Nectar', 434, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', false);
insert into product (provider, name, price, details, avaliable) values ('Blogtags', 'Pecan Raisin - Tarts', 553, 'Donec dapibus. Duis at velit eu est congue elementum.', true);
insert into product (provider, name, price, details, avaliable) values ('Babbleblab', 'Cabbage - Savoy', 645, 'Morbi ut odio.', true);
insert into product (provider, name, price, details, avaliable) values ('InnoZ', 'Soup - Campbells Tomato Ravioli', 458, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', true);
insert into product (provider, name, price, details, avaliable) values ('Dynabox', 'Yogurt - Raspberry, 175 Gr', 488, 'Vestibulum ac est lacinia nisi venenatis tristique.', true);
insert into product (provider, name, price, details, avaliable) values ('Lajo', 'Chickensplit Half', 35, 'Nullam molestie nibh in lectus. Pellentesque at nulla.', false);
insert into product (provider, name, price, details, avaliable) values ('Fatz', 'Soup - Campbells Mac N Cheese', 962, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', true);
insert into product (provider, name, price, details, avaliable) values ('Babblestorm', 'Sansho Powder', 67, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', true);
insert into product (provider, name, price, details, avaliable) values ('Zava', 'Melon - Honey Dew', 53, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', false);
insert into product (provider, name, price, details, avaliable) values ('Npath', 'Urban Zen Drinks', 290, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', false);
insert into product (provider, name, price, details, avaliable) values ('Talane', 'Turkey - Breast, Double', 150, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', false);
insert into product (provider, name, price, details, avaliable) values ('Camimbo', 'Onions - Red', 844, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true);
insert into product (provider, name, price, details, avaliable) values ('Ntag', 'Tea - Green', 304, 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', false);
insert into product (provider, name, price, details, avaliable) values ('Digitube', 'Table Cloth 90x90 White', 631, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', true);
insert into product (provider, name, price, details, avaliable) values ('Skilith', 'Bouillion - Fish', 917, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', true);
insert into product (provider, name, price, details, avaliable) values ('Dynabox', 'French Pastries', 127, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', false);
insert into product (provider, name, price, details, avaliable) values ('Cogidoo', 'Containter - 3oz Microwave Rect.', 807, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', true);
insert into product (provider, name, price, details, avaliable) values ('Shufflebeat', 'Cinnamon Rolls', 521, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', true);
insert into product (provider, name, price, details, avaliable) values ('Zooxo', 'Veal - Leg, Provimi - 50 Lb Max', 374, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', false);
insert into product (provider, name, price, details, avaliable) values ('Wikizz', 'Juice - Lemon', 200, 'Integer a nibh. In quis justo.', true);
insert into product (provider, name, price, details, avaliable) values ('Rhynoodle', 'Cornstarch', 361, 'Vivamus tortor. Duis mattis egestas metus.', false);
insert into product (provider, name, price, details, avaliable) values ('Roodel', 'Mushroom - Shitake, Dry', 144, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', true);
insert into product (provider, name, price, details, avaliable) values ('Vitz', 'Plasticknivesblack', 815, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', false);
insert into product (provider, name, price, details, avaliable) values ('Jabbersphere', 'Energy Drink - Redbull 355ml', 339, 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', false);
insert into product (provider, name, price, details, avaliable) values ('Vidoo', 'Cookies - Oreo, 4 Pack', 105, 'Nunc nisl.', true);
insert into product (provider, name, price, details, avaliable) values ('Thoughtbeat', 'Beans - Black Bean, Preserved', 839, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', true);
insert into product (provider, name, price, details, avaliable) values ('Ntags', 'Beef - Texas Style Burger', 226, 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', true);
insert into product (provider, name, price, details, avaliable) values ('Quinu', 'Bar Nature Valley', 708, 'In sagittis dui vel nisl. Duis ac nibh.', true);
insert into product (provider, name, price, details, avaliable) values ('Meevee', 'Wine - Magnotta - Cab Franc', 963, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', true);
insert into product (provider, name, price, details, avaliable) values ('Eamia', 'Cheese - Cheddar, Old White', 362, 'Nam tristique tortor eu pede.', true);
insert into product (provider, name, price, details, avaliable) values ('Yata', 'Beef - Montreal Smoked Brisket', 864, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', false);
insert into product (provider, name, price, details, avaliable) values ('Skilith', 'Pepper - Cubanelle', 234, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', true);
insert into product (provider, name, price, details, avaliable) values ('Tagpad', 'Shopper Bag - S - 4', 865, 'Nulla nisl. Nunc nisl.', false);
insert into product (provider, name, price, details, avaliable) values ('Youspan', 'Beans - Fine', 875, 'Aliquam erat volutpat.', true);
insert into product (provider, name, price, details, avaliable) values ('Zoomdog', 'Appetizer - Veg Assortment', 727, 'Mauris sit amet eros.', false);
insert into product (provider, name, price, details, avaliable) values ('Meeveo', 'Beans - Kidney White', 104, 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', true);
insert into product (provider, name, price, details, avaliable) values ('Gabtype', 'Wine - Balbach Riverside', 945, 'Nulla ut erat id mauris vulputate elementum.', true);
insert into product (provider, name, price, details, avaliable) values ('Kwideo', 'Pork - Inside', 122, 'Phasellus in felis. Donec semper sapien a libero.', true);
insert into product (provider, name, price, details, avaliable) values ('Gigashots', 'Beans - Black Bean, Canned', 241, 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', false);
insert into product (provider, name, price, details, avaliable) values ('Topdrive', 'Banana Turning', 944, 'Suspendisse accumsan tortor quis turpis. Sed ante.', false);
insert into product (provider, name, price, details, avaliable) values ('Photobean', 'Wheat - Soft Kernal Of Wheat', 356, 'Sed accumsan felis.', false);
insert into product (provider, name, price, details, avaliable) values ('Shuffledrive', 'Tofu - Firm', 315, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', false);
insert into product (provider, name, price, details, avaliable) values ('Zoombox', 'Roe - Lump Fish, Red', 506, 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', false);
insert into product (provider, name, price, details, avaliable) values ('Buzzshare', 'Scampi Tail', 169, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', false);
insert into product (provider, name, price, details, avaliable) values ('Feedbug', 'Soupfoamcont12oz 112con', 878, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', false);
insert into product (provider, name, price, details, avaliable) values ('Buzzbean', 'Onion - Dried', 660, 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', true);
insert into product (provider, name, price, details, avaliable) values ('Kazio', 'Cheese - Bocconcini', 969, 'Duis consequat dui nec nisi volutpat eleifend.', false);
insert into product (provider, name, price, details, avaliable) values ('Tagchat', 'Table Cloth 81x81 White', 354, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', true);
insert into product (provider, name, price, details, avaliable) values ('Edgeify', 'Sugar - Monocystal / Rock', 815, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', true);
insert into product (provider, name, price, details, avaliable) values ('Bluezoom', 'Dried Peach', 56, 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', true);
insert into product (provider, name, price, details, avaliable) values ('Browsetype', 'Oil - Hazelnut', 840, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', false);
insert into product (provider, name, price, details, avaliable) values ('Jabberstorm', 'Bay Leaf Ground', 588, 'Nunc rhoncus dui vel sem. Sed sagittis.', false);
insert into product (provider, name, price, details, avaliable) values ('Feedspan', 'Cheese - Gorgonzola', 294, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', true);
insert into product (provider, name, price, details, avaliable) values ('Jetpulse', 'Wine - Trimbach Pinot Blanc', 539, 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', true);
insert into product (provider, name, price, details, avaliable) values ('Plambee', 'Wine - Savigny - Les - Beaune', 67, 'Donec vitae nisi.', false);
insert into product (provider, name, price, details, avaliable) values ('Thoughtsphere', 'Radish - Black, Winter, Organic', 718, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', false);
insert into product (provider, name, price, details, avaliable) values ('Dabvine', 'Doilies - 7, Paper', 780, 'Aenean fermentum.', false);
insert into product (provider, name, price, details, avaliable) values ('Feedspan', 'Orange - Tangerine', 833, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', true);
insert into product (provider, name, price, details, avaliable) values ('Yodel', 'Lamb - Shoulder', 162, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', true);
insert into product (provider, name, price, details, avaliable) values ('Devpoint', 'Wine - Magnotta - Cab Sauv', 853, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', false);
insert into product (provider, name, price, details, avaliable) values ('Oozz', 'Chocolate - Unsweetened', 724, 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', true);
insert into product (provider, name, price, details, avaliable) values ('Eadel', 'Beans - Fava Fresh', 297, 'Pellentesque ultrices mattis odio. Donec vitae nisi.', true);
insert into product (provider, name, price, details, avaliable) values ('Thoughtstorm', 'Rice Pilaf, Dry,package', 692, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', false);
insert into product (provider, name, price, details, avaliable) values ('Einti', 'Worcestershire Sauce', 218, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', true);
insert into product (provider, name, price, details, avaliable) values ('Babblestorm', 'Cabbage - Green', 54, 'Nunc nisl.', false);
insert into product (provider, name, price, details, avaliable) values ('Babbleopia', 'Red Snapper - Fillet, Skin On', 515, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', false);
insert into product (provider, name, price, details, avaliable) values ('Youopia', 'Wine - Duboeuf Beaujolais', 74, 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', true);
insert into product (provider, name, price, details, avaliable) values ('Topicware', 'Wine - Balbach Riverside', 546, 'Fusce consequat. Nulla nisl.', true);
insert into product (provider, name, price, details, avaliable) values ('Thoughtstorm', 'Cheese Cloth No 60', 303, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', true);
insert into product (provider, name, price, details, avaliable) values ('Babbleset', 'The Pop Shoppe - Lime Rickey', 762, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', true);
insert into product (provider, name, price, details, avaliable) values ('Eare', 'Wine - Bouchard La Vignee Pinot', 344, 'Mauris sit amet eros.', true);
insert into product (provider, name, price, details, avaliable) values ('Gigazoom', 'Arizona - Plum Green Tea', 578, 'Integer tincidunt ante vel ipsum.', true);
insert into product (provider, name, price, details, avaliable) values ('Jabberstorm', 'Veal Inside - Provimi', 301, 'Sed accumsan felis.', false);
insert into product (provider, name, price, details, avaliable) values ('Bluejam', 'Truffle Cups - Red', 462, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', true);
insert into product (provider, name, price, details, avaliable) values ('Devpoint', 'Bacardi Breezer - Strawberry', 416, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', false);
insert into product (provider, name, price, details, avaliable) values ('Viva', 'Quail - Eggs, Fresh', 871, 'Morbi non quam nec dui luctus rutrum.', false);
insert into product (provider, name, price, details, avaliable) values ('Pixonyx', 'Extract - Vanilla,artificial', 249, 'Integer non velit.', false);
insert into product (provider, name, price, details, avaliable) values ('Shuffletag', 'Squid Ink', 823, 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', false);
insert into product (provider, name, price, details, avaliable) values ('Browsezoom', 'Wine - White, Chardonnay', 464, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', false);
insert into product (provider, name, price, details, avaliable) values ('Tazz', 'Pasta - Fettuccine, Egg, Fresh', 408, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', false);
insert into product (provider, name, price, details, avaliable) values ('Thoughtstorm', 'Scampi Tail', 44, 'Mauris lacinia sapien quis libero.', true);
insert into product (provider, name, price, details, avaliable) values ('Trudoo', 'Goldschalger', 489, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', true);
insert into product (provider, name, price, details, avaliable) values ('Vipe', 'Chocolate - Dark Callets', 21, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', true);
insert into product (provider, name, price, details, avaliable) values ('Tambee', 'Energy Drink Red Bull', 916, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', true);
insert into product (provider, name, price, details, avaliable) values ('Janyx', 'Paste - Black Olive', 336, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', true);
insert into product (provider, name, price, details, avaliable) values ('Skyvu', 'Gatorade - Xfactor Berry', 57, 'Praesent blandit. Nam nulla.', false);
insert into product (provider, name, price, details, avaliable) values ('Skipstorm', 'Kohlrabi', 675, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', true);
insert into product (provider, name, price, details, avaliable) values ('Gigazoom', 'Spice - Peppercorn Melange', 901, 'Suspendisse accumsan tortor quis turpis.', false);
insert into product (provider, name, price, details, avaliable) values ('Youfeed', 'Salt - Table', 446, 'Nunc rhoncus dui vel sem.', true);
insert into product (provider, name, price, details, avaliable) values ('Rhycero', 'Marsala - Sperone, Fine, D.o.c.', 511, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', false);
insert into product (provider, name, price, details, avaliable) values ('Linkbridge', 'Pasta - Lasagna, Dry', 856, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', true);
insert into product (provider, name, price, details, avaliable) values ('Dabfeed', 'Wine - Sake', 393, 'Curabitur convallis.', true);
insert into product (provider, name, price, details, avaliable) values ('Kwilith', 'Ice Cream - Strawberry', 323, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', true);
insert into product (provider, name, price, details, avaliable) values ('Meemm', 'Rootbeer', 176, 'Duis consequat dui nec nisi volutpat eleifend.', true);
insert into product (provider, name, price, details, avaliable) values ('LiveZ', 'Lentils - Green, Dry', 584, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', true);
insert into product (provider, name, price, details, avaliable) values ('Trudeo', 'Maintenance Removal Charge', 443, 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', true);
insert into product (provider, name, price, details, avaliable) values ('Tekfly', 'The Pop Shoppe - Root Beer', 540, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', false);
insert into product (provider, name, price, details, avaliable) values ('Bluezoom', 'Sprouts - Onion', 718, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', false);
insert into product (provider, name, price, details, avaliable) values ('Livetube', 'Ecolab - Solid Fusion', 135, 'Nunc purus. Phasellus in felis.', false);
insert into product (provider, name, price, details, avaliable) values ('Blogtags', 'Beans - Navy, Dry', 698, 'Morbi a ipsum. Integer a nibh.', true);
insert into product (provider, name, price, details, avaliable) values ('Skyba', 'Salmon - Atlantic, Skin On', 402, 'Maecenas ut massa quis augue luctus tincidunt.', true);
insert into product (provider, name, price, details, avaliable) values ('Quimm', 'Carbonated Water - White Grape', 682, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', false);
insert into product (provider, name, price, details, avaliable) values ('Shufflester', 'Artichoke - Fresh', 634, 'Mauris sit amet eros.', false);
insert into product (provider, name, price, details, avaliable) values ('Meeveo', 'Southern Comfort', 818, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', false);
insert into product (provider, name, price, details, avaliable) values ('Youspan', 'Hummus - Spread', 909, 'Morbi a ipsum.', true);
insert into product (provider, name, price, details, avaliable) values ('Roombo', 'Shrimp - Black Tiger 16/20', 155, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', false);
insert into product (provider, name, price, details, avaliable) values ('DabZ', 'Cardamon Seed / Pod', 407, 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', false);
insert into product (provider, name, price, details, avaliable) values ('Digitube', 'Bread Base - Italian', 486, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', true);
insert into product (provider, name, price, details, avaliable) values ('Blognation', 'Table Cloth 144x90 White', 944, 'Praesent blandit lacinia erat.', false);
insert into product (provider, name, price, details, avaliable) values ('Vinder', 'Hummus - Spread', 438, 'Cras pellentesque volutpat dui.', false);
insert into product (provider, name, price, details, avaliable) values ('Eire', 'Cumin - Whole', 65, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', false);
insert into product (provider, name, price, details, avaliable) values ('Oodoo', 'Pur Source', 297, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', true);
insert into product (provider, name, price, details, avaliable) values ('Eamia', 'Bagel - Everything', 655, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', false);
insert into product (provider, name, price, details, avaliable) values ('Cogibox', 'Mint - Fresh', 304, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', true);
insert into product (provider, name, price, details, avaliable) values ('Zooxo', 'Sauce - Ranch Dressing', 50, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', false);
insert into product (provider, name, price, details, avaliable) values ('Jabbertype', 'Ecolab - Hand Soap Form Antibac', 784, 'Vestibulum rutrum rutrum neque.', false);
insert into product (provider, name, price, details, avaliable) values ('Oloo', 'Chocolate - Dark Callets', 33, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', false);
insert into product (provider, name, price, details, avaliable) values ('Twitterbridge', 'Kahlua', 658, 'Donec posuere metus vitae ipsum. Aliquam non mauris.', true);
insert into product (provider, name, price, details, avaliable) values ('Zoomdog', 'Gelatine Leaves - Envelopes', 970, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', false);
insert into product (provider, name, price, details, avaliable) values ('Eayo', 'Wine - Chateau Bonnet', 258, 'Vestibulum sed magna at nunc commodo placerat.', true);
insert into product (provider, name, price, details, avaliable) values ('Kare', 'Ezy Change Mophandle', 947, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', true);
insert into product (provider, name, price, details, avaliable) values ('Dabvine', 'Energy Drink - Redbull 355ml', 288, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', false);
insert into product (provider, name, price, details, avaliable) values ('Gabtune', 'Wine - Tribal Sauvignon', 731, 'Integer a nibh.', false);
insert into product (provider, name, price, details, avaliable) values ('Ainyx', 'Nut - Chestnuts, Whole', 929, 'Nunc rhoncus dui vel sem. Sed sagittis.', false);
insert into product (provider, name, price, details, avaliable) values ('Thoughtbeat', 'Chicken - Whole', 158, 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', true);
insert into product (provider, name, price, details, avaliable) values ('Buzzshare', 'Crackers - Water', 992, 'Vestibulum rutrum rutrum neque.', true);
insert into product (provider, name, price, details, avaliable) values ('Leexo', 'Soup - Knorr, Chicken Gumbo', 858, 'Praesent blandit.', false);
insert into product (provider, name, price, details, avaliable) values ('Rhyloo', 'Liqueur Banana, Ramazzotti', 917, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', false);
insert into product (provider, name, price, details, avaliable) values ('Skimia', 'Mahi Mahi', 569, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', false);
insert into product (provider, name, price, details, avaliable) values ('Skajo', 'Longos - Lasagna Beef', 972, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', true);
insert into product (provider, name, price, details, avaliable) values ('Zooveo', 'Cocoa Powder - Dutched', 230, 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', true);
insert into product (provider, name, price, details, avaliable) values ('Zazio', 'Wine - Cabernet Sauvignon', 977, 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', true);
insert into product (provider, name, price, details, avaliable) values ('Jatri', 'Tart - Lemon', 298, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', false);
insert into product (provider, name, price, details, avaliable) values ('Ailane', 'Juice - Orange 1.89l', 828, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', true);
insert into product (provider, name, price, details, avaliable) values ('Flashpoint', 'Rosemary - Primerba, Paste', 838, 'Fusce posuere felis sed lacus.', false);
insert into product (provider, name, price, details, avaliable) values ('Innojam', 'Chicken - Livers', 538, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', false);
insert into product (provider, name, price, details, avaliable) values ('Babbleset', 'Tomatoes - Vine Ripe, Yellow', 443, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', false);
insert into product (provider, name, price, details, avaliable) values ('Aivee', 'Potatoes - Mini Red', 180, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', true);
insert into product (provider, name, price, details, avaliable) values ('Twitterbeat', 'Rum - Coconut, Malibu', 442, 'Nam tristique tortor eu pede.', true);
insert into product (provider, name, price, details, avaliable) values ('Cogibox', 'Soup - Campbells, Spinach Crm', 605, 'In sagittis dui vel nisl.', true);
insert into product (provider, name, price, details, avaliable) values ('Livefish', 'Soup - Campbells Chili Veg', 580, 'Nunc purus.', true);
insert into product (provider, name, price, details, avaliable) values ('Gabtune', 'Longos - Chicken Curried', 963, 'Vivamus tortor. Duis mattis egestas metus.', false);
insert into product (provider, name, price, details, avaliable) values ('Twiyo', 'Wine - Lamancha Do Crianza', 740, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', true);
insert into product (provider, name, price, details, avaliable) values ('Plambee', 'Pomegranates', 849, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', true);
insert into product (provider, name, price, details, avaliable) values ('Edgepulse', 'Sorrel - Fresh', 431, 'Duis mattis egestas metus. Aenean fermentum.', false);
insert into product (provider, name, price, details, avaliable) values ('Kayveo', 'Salmon - Atlantic, Fresh, Whole', 123, 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', true);
insert into product (provider, name, price, details, avaliable) values ('Thoughtstorm', 'Pasta - Spaghetti, Dry', 756, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', true);
insert into product (provider, name, price, details, avaliable) values ('Skajo', 'Flower - Commercial Spider', 836, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', true);
insert into product (provider, name, price, details, avaliable) values ('Quimba', 'Nectarines', 171, 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', true);
insert into product (provider, name, price, details, avaliable) values ('Blogtags', 'Flour - Cake', 692, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', true);
insert into product (provider, name, price, details, avaliable) values ('Meemm', 'Table Cloth 81x81 White', 305, 'Maecenas tincidunt lacus at velit.', true);
insert into product (provider, name, price, details, avaliable) values ('Photospace', 'Sauce - Sesame Thai Dressing', 318, 'Donec quis orci eget orci vehicula condimentum.', false);
insert into product (provider, name, price, details, avaliable) values ('Skipstorm', 'Bread - Pita', 836, 'Aliquam erat volutpat.', false);
insert into product (provider, name, price, details, avaliable) values ('Skimia', 'Jam - Raspberry', 698, 'Maecenas pulvinar lobortis est.', true);
insert into product (provider, name, price, details, avaliable) values ('InnoZ', 'Energy Drink', 910, 'Suspendisse accumsan tortor quis turpis.', false);
insert into product (provider, name, price, details, avaliable) values ('Yata', 'Longos - Lasagna Veg', 205, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', true);
insert into product (provider, name, price, details, avaliable) values ('Kaymbo', 'Soup - Campbells, Butternut', 596, 'Vivamus tortor.', false);
insert into product (provider, name, price, details, avaliable) values ('Voomm', 'Doilies - 5, Paper', 245, 'Maecenas pulvinar lobortis est.', false);
insert into product (provider, name, price, details, avaliable) values ('Photobug', 'Muffin Mix - Oatmeal', 992, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', false);
insert into product (provider, name, price, details, avaliable) values ('Youtags', 'Marsala - Sperone, Fine, D.o.c.', 162, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', false);
insert into product (provider, name, price, details, avaliable) values ('Plambee', 'Muffin - Banana Nut Individual', 665, 'Nunc rhoncus dui vel sem.', false);
insert into product (provider, name, price, details, avaliable) values ('Zoombox', 'Wine - Magnotta, Merlot Sr Vqa', 688, 'Quisque ut erat.', false);
insert into product (provider, name, price, details, avaliable) values ('Shufflebeat', 'Iced Tea - Lemon, 460 Ml', 970, 'Donec dapibus. Duis at velit eu est congue elementum.', true);
insert into product (provider, name, price, details, avaliable) values ('Snaptags', 'Cardamon Seed / Pod', 237, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', true);
insert into product (provider, name, price, details, avaliable) values ('Gigabox', 'Cookies - Englishbay Oatmeal', 391, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', false);
insert into product (provider, name, price, details, avaliable) values ('Viva', 'Wine - Chablis 2003 Champs', 915, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', true);
insert into product (provider, name, price, details, avaliable) values ('Meemm', 'Roe - Lump Fish, Black', 570, 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', true);
insert into product (provider, name, price, details, avaliable) values ('Demivee', 'Ginger - Fresh', 123, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', true);
insert into product (provider, name, price, details, avaliable) values ('Realfire', 'Foil Cont Round', 863, 'Etiam faucibus cursus urna. Ut tellus.', false);
insert into product (provider, name, price, details, avaliable) values ('Twitterwire', 'Tart Shells - Savory, 2', 521, 'Mauris ullamcorper purus sit amet nulla.', true);
insert into product (provider, name, price, details, avaliable) values ('Yodoo', 'Mustard - Dry, Powder', 75, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', true);
insert into product (provider, name, price, details, avaliable) values ('Voolia', 'Rhubarb', 387, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', false);
insert into product (provider, name, price, details, avaliable) values ('Skivee', 'Water - Aquafina Vitamin', 64, 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', false);
insert into product (provider, name, price, details, avaliable) values ('Topicstorm', 'Glass Clear 8 Oz', 252, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', true);
insert into product (provider, name, price, details, avaliable) values ('Realcube', 'Apples - Spartan', 256, 'Curabitur convallis.', false);
insert into product (provider, name, price, details, avaliable) values ('Skinte', 'Creamers - 10%', 547, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', true);
insert into product (provider, name, price, details, avaliable) values ('Thoughtbridge', 'Filter - Coffee', 113, 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', false);
insert into product (provider, name, price, details, avaliable) values ('Trudeo', 'Broom - Corn', 225, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', false);
insert into product (provider, name, price, details, avaliable) values ('Pixope', 'Pasta - Penne, Rigate, Dry', 100, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', false);
insert into product (provider, name, price, details, avaliable) values ('Meezzy', 'Longos - Chicken Caeser Salad', 890, 'Duis consequat dui nec nisi volutpat eleifend.', false);
insert into product (provider, name, price, details, avaliable) values ('Thoughtbridge', 'Squash - Sunburst', 835, 'Etiam pretium iaculis justo.', true);
insert into product (provider, name, price, details, avaliable) values ('Yakidoo', 'Beef - Ox Tongue', 964, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', true);
insert into product (provider, name, price, details, avaliable) values ('Gabtype', 'Trout - Rainbow, Fresh', 926, 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', true);
